### ISSUE TITLE
大佬有没有考虑做个webui？

### ISSUE THREAD

**Issue by theoldsong** [muzishen/IMAGDressing#13]
这样操作更方便

**Comment by yvrjsharma** [comment]
Hi @muzishen, it would be really helpful to have the huggingface Spaces demo available locally, with a link and setup instructions in the README. Makes it so much easier to test and contribute. 

It could be similar to the LivePortrait repo- https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#4-gradio-interface- 

ImageDressing-v1 demo on Huggingface Spaces:
![image](https://github.com/user-attachments/assets/7e3c14b6-09fd-46b8-a75d-0d675998507f)
