### ISSUE TITLE
Whe training data is ready to download?

### ISSUE THREAD

**Issue by caiqi** [muzishen/IMAGDressing#14]
Is there a timeline when training data will be released? Thanks!

**Comment by muzishen** [comment]
We're working on it, about 1 week.

**Comment by pennypengpm** [comment]
+1, thanks

**Comment by Baicheng42** [comment]
+2, many thanks

**Comment by muzishen** [comment]
Thanks to your attention and star, we can confirm that the data release will be completed in the coming week.

**Comment by fujianhai** [comment]
+1 , thanks many

**Comment by Limbor** [comment]
Hello, will the data be ready soon? Thanks!

**Comment by Limbor** [comment]
Hello, will you make the dataset public in the near future? Thanks!

**Comment by caiqi** [comment]
@muzishen Thanks for the awesome work! Do you have a timeline when the data will be released?

**Comment by muzishen** [comment]
The IGPiar dataset is now open for request and download.

**Comment by caiqi** [comment]
> The IGPiar dataset is now open for request and download.

Thanks! I have applied for the dataset. Hope you can approve it soon.
