### ISSUE TITLE
change to models/image_encoder

### ISSUE THREAD

**Issue by da2r-20** [muzishen/IMAGDressing#17]
https://github.com/muzishen/IMAGDressing/blob/57254f8afb5100433d6ef3e4c888384789af64c6/inference_IMAGdressing_controlnetpose.py#L52

should be changed to :
```python
image_encoder = CLIPVisionModelWithProjection.from_pretrained("h94/IP-Adapter", subfolder="models/image_encoder").to( 
```

**Comment by muzishen** [comment]
Thanks.
