### ISSUE TITLE
I tried your demo and I feel that the face is not well restored and the hands are severely deformed. Can we use face adapter or Pulid algorithms to improve it? It would be best if the user sends a full body picture of themselves, and they can change it based on the image without the need to input posture

### ISSUE THREAD

**Issue by libai-lab** [muzishen/IMAGDressing#2]
I tried your demo and I feel that the face is not well restored and the hands are severely deformed. Can we use face adapter or Pulid algorithms to improve it? It would be best if the user sends a full body picture of themselves, and they can change it based on the image without the need to input posture

**Comment by muzishen** [comment]
Very cool idea, but the original idea of this project is for merchants to customize and advertise their clothes. In the near future, we will be supporting customer specific areas of clothing, but may need to give us some time to iterate. But please be assured that we will improve these as much as possible. In addition, regarding faces and details, the upcoming large-scale weights will solve part of the problem. Further details will be addressed in the v2 release. Thank you for your attention!

**Comment by muzishen** [comment]
We already support this feature, although it is not the best, but I believe we will continue to improve in future versions.
