### ISSUE TITLE
installation issues in windows

### ISSUE THREAD

**Issue by thewayur** [muzishen/IMAGDressing#20]
Hi, i am pretty new to conda, after multiple struggles and searches i ended up with below error in conda mini
![with conda](https://github.com/user-attachments/assets/cae43683-5192-43b9-88f4-a8482adeb7e7)

Also when i m trying without conda i m getting this error
![without conda](https://github.com/user-attachments/assets/8461d539-7d5e-43ba-8512-174dbdabc5b9)

Please suggest some solutions.

Also when i was using normal conda, i was getting wierd error (git was installed): 
fatal: not a git repository (or any of the parent directories): .git conda environment 

PS: my other AI tools like A1111, comfyui etc are working fine.

**Comment by S1D007** [comment]
same here bruh. pure piece of shit
