### ISSUE TITLE
Reference Image

### ISSUE THREAD

**Issue by rohitpaul23** [muzishen/IMAGDressing#26]
Thank You for the wonderful paper

I have some doubt regarding the reference image used:
1. As it seems you have used your own data. similar to that of VITON HD and Dresscode. Whether you are following any structure or alignment which is common to all or any flat lay garment will work?
2. And if so how the model understand the size of the garment (mini, macro, half, full, ..) 
3. and in contrast to OOTDiffusion where a category is passed (upper_body, lower_body, dresses), how it is determined here. Given a garment can have varied uncommon structure

**Comment by muzishen** [comment]
Thank you for your interest in our project! The training code is now available. If you find our work helpful, please **star** our repository and **cite** us in your work.
