### ISSUE TITLE
FileNotFoundError: IMAGDressing-v1_512.pt

### ISSUE THREAD

**Issue by llu43** [muzishen/IMAGDressing#27]
I'm trying to use the IMAGDressing project but I'm encountering a `FileNotFoundError` for the file `IMAGDressing-v1_512.pt`. I couldn't find any information in the documentation about where to obtain this file.

Could you please provide guidance on where to download this file or how to generate it?

I also have another error: NameError: name 'LoraLoaderMixin' is not defined

Thank you!

**Comment by llu43** [comment]
I found the file here: https://huggingface.co/feishen29/IMAGDressing but when I try to load it, I have this error: Traceback (most recent call last):
  File "/Workspace/Shared/data_science/GenAI/Nuria Llopart/IMAGDressing2/inference_IMAGdressing.py", line 154, in <module>
    pipe, generator = prepare(args)
                      ^^^^^^^^^^^^^
  File "/Workspace/Shared/data_science/GenAI/Nuria Llopart/IMAGDressing2/inference_IMAGdressing.py", line 97, in prepare
    model_sd = torch.load(args.model_ckpt, map_location="cpu")["module"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/databricks/python/lib/python3.11/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by muzishen** [comment]
Thank you for your attention, it seems that your downloaded weights are incomplete
