### ISSUE TITLE
Questions regarding the dataset

### ISSUE THREAD

**Issue by caiqi** [muzishen/IMAGDressing#38]
Is it expected that certain images appear multiple times within the dataset? For instance, the following image appears 144 times.

![image](https://github.com/user-attachments/assets/e897b756-0604-4cbc-8d8b-99ac55cec447)

![image](https://github.com/user-attachments/assets/cd917ab3-5c4f-4b04-a1e2-789f179c6bf5)

**Comment by muzishen** [comment]
Please check that the corresponding clothing path in json is different.

**Comment by caiqi** [comment]
Thanks! I check that the cloth path is different but the cloth image are very similar, only different in colors. 

Another question is should the cloth should be paired with human image? For example, a red T-shirt should not be paired with human wearing a yellow T-shirt?

**Comment by caiqi** [comment]
Indeed, this dataset is undoubtedly beneficial to the entire community. I am closing this issue.
