### ISSUE TITLE
IGPair.zip压缩文件格式未知或者数据已经被损坏

### ISSUE THREAD

**Issue by Preciousrs** [muzishen/IMAGDressing#39]
cat IGPair.zip.* > IGPair.zip 之后 解压IGPair.zip 出现以下问题

![image](https://github.com/user-attachments/assets/81de0a41-98b5-48a1-b4ad-623853db163c)

**Comment by muzishen** [comment]
It seems to be the cause of incomplete file download

**Comment by ayd-ocan** [comment]
I got same error too, and I think that problem is related with zip file, not download status.

**Comment by muzishen** [comment]
#38

**Comment by muzishen** [comment]
#38 But everything seemed norma.
