### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by cmd-d** [muzishen/IMAGDressing#4]
Already installed in my env pip, torch-2.1.0+cu118

CUDA_HOME exists, and nvcc is 11.8.

However, I'm getting this error when running pip install -r requirements.txt

...
Collecting deepspeed==0.14.1 (from -r requirements.txt (line 11))
  Using cached deepspeed-0.14.1.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      C:\Users\User\anaconda3\envs\imag\lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      test.c
      LINK : fatal error LNK1181: no se puede abrir el archivo de entrada 'aio.lib'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-z97g9w67\deepspeed_c6daba0ee84e4b7a8ea423e02b7a709f\setup.py", line 180, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\User\AppData\Local\Temp\pip-install-z97g9w67\deepspeed_c6daba0ee84e4b7a8ea423e02b7a709f\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

_____
I tried to manually install deepspeed==0.14.1., but still get a lot of dependencies conflicts.

**Comment by WhiteJiang** [comment]
If you just want to try our model, you don't need to install deepseed, and installing deepseed on Unbuntu may be the preferred option.
