### ISSUE TITLE
Quality of Outfit Changing Feature

### ISSUE THREAD

**Issue by AniketRajpoot** [muzishen/IMAGDressing#41]
Hello authors! 
Thank you for the great work! 

I was trying to use the experimental feature of outfit changing and after successfully setting it up, I am not getting very good results ? 

Do you have any suggestions to improve the quality ? I am attaching the samples for you to check, please tell me what am I doing wrong ? I am very new to this field so please forgive me for my lack of knowledge! 

Thanks a lot! 

<img width="512" alt="09_upper" src="https://github.com/user-attachments/assets/725b299b-8b0c-4d70-9622-7bad34e1b2d5">
<img width="512" alt="09_upper" src="https://github.com/user-attachments/assets/3a4366d3-2b81-4834-99f4-fd8d1a5303de">

**Comment by muzishen** [comment]
The above image seems to be too large cfg, you can adjust the parameters, you can try our webui to see what the result is.
The problem below is that we currently only support giving a single garment, not the model wearing the garment.

**Comment by AniketRajpoot** [comment]
Below are the parameters : 

<img width="228" alt="image" src="https://github.com/user-attachments/assets/fbb8ec21-a3f2-4374-94b9-2ff5dce773f9">

do you think these are optimal I am talking about ```inference_IMAGdressing_controlnetinpainting.py``` script ? 

Thanks in advance!
