### ISSUE TITLE
Question about training?

### ISSUE THREAD

**Issue by cyysc1998** [muzishen/IMAGDressing#44]
Thanks for the great work! I try to reproduce the work with "run.py" in the repo. I use the same pretrained sd weight and hyper parameters in "run.py", except for bs=16 and num_gpu=16 in my experiment. I train the model about 60k steps and it seems the training crashed. I get a strange image as follows. Could you me some hints?
![image](https://github.com/user-attachments/assets/f277f115-a2c2-4e51-bc50-cac67da0fff2)

**Comment by muzishen** [comment]
When it comes to reasoning. img scale is big, try to turn it down, look forward to your results.

**Comment by cyysc1998** [comment]
Hello, reducing the image scale only reduces the similarity between the generated image and the clothing image, but the image is still broken. Could you share your training config? Thank you!

**Comment by muzishen** [comment]
Please email to me if you willing. And we can communicate deeply, thanks!
