### ISSUE TITLE
How do I convert checkpoint files into a single .bin file?

### ISSUE THREAD

**Issue by Bilgee** [muzishen/IMAGDressing#45]
Thank you for your great work. I trained your model on our custom dataset. In the checkpoint folder, there are two files: mp_rank_00_model_states.pt and zero_pp_rank_0_mp_rank_00_optim_states.pt etc. I am not familiar with deepspeed, and how can I convert them into a single checkpoint file?

**Comment by muzishen** [comment]
Maybe you can refer to the IP-Adapter
