### ISSUE TITLE
Confusion about IGPair dataset 

### ISSUE THREAD

**Issue by Inception41** [muzishen/IMAGDressing#46]
Thank you for your nice work. I have a question about the data. For example, image_000000_00.jpg corresponds to cloth_000000.jpg, and their corresponding cloth_type is upper_body, but cloth_000000.jpg is a pair of pants, shouldn’t the cloth_type be lower_body?

**Comment by muzishen** [comment]
Hello, there is a partial error in type. 
We are working on the second version. 
But it does not affect the training IMAGDressing-v1.
