### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by ChandlerSun14** [muzishen/IMAGDressing#47]
Hi,

I came across an issue when trying to train the model based on existing data sets

It seems the current diffusers v0.24 can't load the unet weight, which was stated officially with diffusers=0.16.1. Any advices are much appreciated. 

Note that it is not gone work even with diffusers v0.16.1 as it would throw other issue as well

File "train.py", line 321, in main
    unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
  File "/home/chandler/Tools/miniconda3/envs/IMAGDressing/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 805, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'> from pretrained/control_v11p_sd15_openpose/ because the following keys are missing: 
 up_blocks.1.attentions.2.transformer_blocks.0.attn1.to_out.0.bias, up_blocks.1.resnets.0.conv2.weight, up_blocks.2.attentions.2.transformer_blocks.0.attn1.to_k.weight, up_blocks.0.resnets.1.conv2.bias, up_blocks.3.attentions.0.transformer_blocks.0.norm3.weight, up_blocks.0.resnets.2.conv1.bias, up_blocks.1.resnets.0.norm1.bias, up_blocks.3.attentions.2.transformer_blocks.0.attn2.to_k.weight, up_blocks.3.resnets.0.conv_shortcut.weight, up_blocks.1.attentions.2.transformer_blocks.0.attn2.to_k.weight, up_blocks.2.attentions

**Comment by muzishen** [comment]
Sorry, I just saw the message now, may I ask if you have solved it

**Comment by ChandlerSun14** [comment]
Yes I have figured it out. thanks for checking
