### ISSUE TITLE
Could you offer the face_path to let me evaluate,thanks

### ISSUE THREAD

**Issue by linlinx666** [muzishen/IMAGDressing#52]
Could you offer the IGPair's face_path to let me evaluate,thanks

**Comment by muzishen** [comment]
@WhiteJiang  Please help to answer this Q，thanks !

**Comment by WhiteJiang** [comment]
@linlinx666 Please contact xinjiang@njust.edu.cn and we will provide the face file we use.

**Comment by linlinx666** [comment]
thank u,already get the face file
